### ISSUE TITLE
Wallet for OSX 10.13

### ISSUE THREAD

**Issue by greydaymine** [monacocoin-net/monoeci-core#3]
Crashes on opening (osx 10.13.2); receiving the following error:

DYLD, [0x1] Library missing

Detailed error message:

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/monoeci-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

**Comment by scatcher** [comment]
Same issue here.  Errors out when starting.

![problem_report_for_monoeci-qt](https://user-images.githubusercontent.com/1429656/33798468-79fd955a-dccd-11e7-8ba9-ccd859b9d3fd.png)

**Comment by Lazzaa** [comment]
Same issue. Please repair. Setting up masternode.

**Comment by akriv-git** [comment]
Got the same error.  On the bottom of the README, there is a link for instructions to install the boost libraries. Those instructions say to use homebrew to install boost, which I did.  Still the same error.  To workaround the issue, navigate to /usr/local/lib and run this command:
ln -s /usr/local/Cellar/boost/1.66.0/lib/libboost_system-mt.dylib libboost_system-mt.dylib

This command adds a symbolic link to the missing boost library installed by homebrew.  Adding it to the path didn't work (or didn't stick) for me.  After doing this, the wallet installed.  Also, trying to get a masternode up and running.  Good luck.

**Comment by MarkJWhittaker** [comment]
I have a mac and I've downloaded the wallet for 10.13 and the software cannot open... Has anyone found a solution? This is not good as I want to set up a Masternode...

**Comment by jongkwang** [comment]
Still the same problem
When I run it does not work.

#### Environment
- macOS : version 10.13.3
- wallet : monoeciCore-0.12.2-wallet-macOs10.13.dmg

**Comment by jongkwang** [comment]
Oh.. in my case, Solved.
When I run it does not work. just not work. *I did not see above message*

I came to see on the bottom of the [Release Notes](https://github.com/monacocoin-net/monoeci-core/releases) later.
and solved.

**Comment by Yoyae** [comment]
Sorry to answer that late, you issue might have been solve already. If not, check the new version.
I'm closing this. If you feel the new version doesn't address the issue feel free to open a new one.
