### ISSUE TITLE
coin missing after closing and opening core wallet

### ISSUE THREAD

**Issue by mandimesd** [monacocoin-net/monoeci-core#4]
I closed my wallet and reopened it.  All my coin as long as my old address and label were also gone.  I was able to find my missing coin using some commands provided in the wallet but is now only available as "watch-only".  My wallet was encrypted and I have the code so how do I recover my coin?

want to support this crypto but man this is ridiculous.

**Comment by Yoyae** [comment]
Sorry to answer that late, you issue might have been solve already. If not, check the new version.
I'm closing this. If you feel the new version doesn't address the issue feel free to open a new one.
