### ISSUE TITLE
Updating Masternode - error Libraries after executing monoecid 

### ISSUE THREAD

**Issue by Icefox2k** [monacocoin-net/monoeci-core#6]
When running the command: monoecid
I get the following error message:
monoecid: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory

What can I do?

Thanks for everybody who response.

**Comment by Lercker** [comment]
I actually have the same problem. I have been meaning to go on discord to ask this but haven't had the time recently. Hopefully someone has an answer.

**Comment by Lercker** [comment]
sudo apt-get -y install libzmq3-dev
Run this under your root user and everything should work out.

**Comment by Icefox2k** [comment]
Thanks for your answers - everything works fine now
