### ISSUE TITLE
new wallet for Mac not worked

### ISSUE THREAD

**Issue by bekman1** [monacocoin-net/monoeci-core#7]
Hi guys, downloaded newest wallet, my Mac on Mac OS 10.13.2 (High Siera)
Cant start wallet, crash on start!

 Error report:

`
Process:               monoeci-Qt [1408]
Path:                  /Applications/WALLETS/monoeci-Qt.app/Contents/MacOS/monoeci-Qt
Identifier:            org.monoeci.monoeci-Qt
Version:               0.12.2 (0.12.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           monoeci-Qt [1408]
User ID:               501

Date/Time:             2017-12-24 18:55:57.616 +0100
OS Version:            Mac OS X 10.13.2 (17C88)
Report Version:        12
Anonymous UUID:        25AF0B8A-F86D-76E4-D28D-1196FA66297C

Time Awake Since Boot: 1200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x10f3bb000 -        0x10fe91ff7 +org.monoeci.monoeci-Qt (0.12.2 - 0.12.2) <4701A0E6-6D84-3982-9D52-1FFC28BBDF95> /Applications/WALLETS/monoeci-Qt.app/Contents/MacOS/monoeci-Qt
       0x10ffda000 -        0x11002dff7 +libzmq.5.dylib (0) <F7B973DE-A175-361A-8131-334BCDCF6BB4> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libzmq.5.dylib
       0x110041000 -        0x110043ff7 +libboost_system.dylib (0) <D72B83E6-527A-30C8-A767-CF658E84FBAC> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x110049000 -        0x110058ff7 +libboost_filesystem.dylib (0) <7EB22425-F98A-3200-8C76-512946198C83> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x110068000 -        0x110099fff +libboost_program_options-mt.dylib (0) <ECEECCE3-7ABA-3758-BBB4-1D47C3560F8F> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x1100bc000 -        0x1100c9fff +libboost_thread-mt.dylib (0) <40ED37AC-99FD-3039-AB13-B3ACB21DB32F> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x1100d4000 -        0x1100d5ffb +libboost_chrono-mt.dylib (0) <224627E3-7526-3794-A091-16E67D877742> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x1100dc000 -        0x1101e3ff7 +QtNetwork (5.5.1) <883A53FB-7857-34BC-B732-F23592EA3B26> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x11021a000 -        0x110711ff7 +QtWidgets (5.5.1) <51985D53-4933-38E5-A842-DC85D15F5F8C> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x11084e000 -        0x110ce0ff7 +QtGui (5.5.1) <5C681010-C0B3-36D9-BD77-3BDC232EF97F> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x110dbe000 -        0x1112bdff7 +QtCore (5.5.1) <73946C22-5E05-3FD4-B5D5-B0DBCD039222> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x11134e000 -        0x1113b0ff7 +QtDBus (5.5.1) <27A55C14-E871-3DBE-8538-87D711FFAB35> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x1113c8000 -        0x1114eeff3 +libprotobuf.14.dylib (0) <FAA23550-6459-3B0B-9053-0491A24DA85F> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libprotobuf.14.dylib
       0x11159a000 -        0x1116b4ff3 +libdb_cxx-4.8.dylib (0) <A961AAB6-ED4B-36F5-846E-F8B24D4FFFC8> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x1116f0000 -        0x111731fff +libssl.1.0.0.dylib (0) <A0B6C569-8EE4-35AA-880C-17E0A5CBDE97> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x111754000 -        0x1118c4c7f +libcrypto.1.0.0.dylib (0) <0220EA16-4B7D-30E9-8281-1AAC5A1965D8> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x11192d000 -        0x111935ff3 +libminiupnpc.16.dylib (0) <FD041313-B0A5-3A91-B905-4FF19CB15D04> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x11193f000 -        0x111940fff +libevent_pthreads-2.1.6.dylib (0) <32AC3368-70B7-32B4-8465-50FA643C2649> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x111945000 -        0x111971ff7 +libevent-2.1.6.dylib (0) <B4866E97-7CC4-3E15-BF2C-F667971CE7C7> /Applications/WALLETS/monoeci-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x11e4c7000 -        0x11e51198f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
    0x7fff41d25000 -     0x7fff42b82fff  com.apple.AppKit (6.9 - 1561.20.106) <7A71ACCF-2DF5-3557-BB22-3A9FC9F71CCF> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff42bd4000 -     0x7fff42bd4fff  com.apple.ApplicationServices (48 - 50) <7627DBD6-497B-3AB7-9B63-F0532EDF09B8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff446ff000 -     0x7fff44b9ffff  com.apple.CoreFoundation (6.9 - 1450.16) <23F8373A-FA3F-37A2-BA5B-70061BFCCD21> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff4585e000 -     0x7fff4585efff  com.apple.CoreServices (822.19 - 822.19) <0C60B639-4CC4-3F57-BC5E-DB71EB75F7F4> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff46843000 -     0x7fff46c08fff  com.apple.Foundation (6.9 - 1450.16) <7FEC6610-70EA-3A8D-8EC4-7E99BAF1E312> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff698bb000 -     0x7fff698eefff  libclosured.dylib (519.2.2) <48051216-5647-3643-B979-B77D0FD20011> /usr/lib/closure/libclosured.dylib
    0x7fff69dcd000 -     0x7fff69dceff3  libSystem.B.dylib (1252) <5EDEEA85-0387-31EE-9D9B-DA1B75E7AEF3> /usr/lib/libSystem.B.dylib
    0x7fff6a001000 -     0x7fff6a057fff  libc++.1.dylib (400.9) <FCF5E1F6-2B04-3545-8004-F3AB32FED172> /usr/lib/libc++.1.dylib
    0x7fff6a058000 -     0x7fff6a07cff7  libc++abi.dylib (400.7) <217656D5-BC40-37FF-B322-91CB2AAD4F34> /usr/lib/libc++abi.dylib
    0x7fff6b3ce000 -     0x7fff6b7bc7e7  libobjc.A.dylib (723) <93A92316-DE1E-378C-8891-99720B50D075> /usr/lib/libobjc.A.dylib
    0x7fff6be69000 -     0x7fff6be6dff7  libcache.dylib (80) <354F3B7D-404E-3398-9EBF-65CA2CE65211> /usr/lib/system/libcache.dylib
    0x7fff6be6e000 -     0x7fff6be78ff3  libcommonCrypto.dylib (60118.30.2) <674286D3-7744-36A3-9AAA-49DFCD97A986> /usr/lib/system/libcommonCrypto.dylib
    0x7fff6be79000 -     0x7fff6be80fff  libcompiler_rt.dylib (62) <4487CFBA-A5D7-3282-9E6B-94CAD7BE507E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff6be81000 -     0x7fff6be89ffb  libcopyfile.dylib (146.30.2) <2C7C67D7-562B-3FFA-973D-BACF4C10E1EC> /usr/lib/system/libcopyfile.dylib
    0x7fff6be8a000 -     0x7fff6bf0ffff  libcorecrypto.dylib (562.30.10) <8A53EFE1-AFCA-3676-BEE1-FA5ED9F0E222> /usr/lib/system/libcorecrypto.dylib
    0x7fff6bf97000 -     0x7fff6bfd0ff7  libdispatch.dylib (913.30.4) <7D0E3183-282B-3FEE-A734-2C0ADC092084> /usr/lib/system/libdispatch.dylib
    0x7fff6bfd1000 -     0x7fff6bfeeff7  libdyld.dylib (519.2.2) <C50D02BC-A333-3313-B787-02F255A6783F> /usr/lib/system/libdyld.dylib
    0x7fff6bfef000 -     0x7fff6bfefffb  libkeymgr.dylib (28) <6D84A96F-C65B-38EC-BDB5-21FD2C97E7B2> /usr/lib/system/libkeymgr.dylib
    0x7fff6bffd000 -     0x7fff6bffdff7  liblaunch.dylib (1205.30.29) <E66F58ED-C15E-3DFB-BC22-A861E13918C6> /usr/lib/system/liblaunch.dylib
    0x7fff6bffe000 -     0x7fff6c002ffb  libmacho.dylib (900.0.1) <756F2553-07B6-3B42-ACEA-2F0F1A5E8D0F> /usr/lib/system/libmacho.dylib
    0x7fff6c003000 -     0x7fff6c005ff3  libquarantine.dylib (86) <6AC8773F-3817-3D82-99C2-01BABB9C3CBB> /usr/lib/system/libquarantine.dylib
    0x7fff6c006000 -     0x7fff6c007ff3  libremovefile.dylib (45) <912FA211-DD8C-3C92-8424-21B89F8B10FD> /usr/lib/system/libremovefile.dylib
    0x7fff6c008000 -     0x7fff6c01ffff  libsystem_asl.dylib (356.1.1) <94972913-9DF0-3C78-847C-43E58919E3DA> /usr/lib/system/libsystem_asl.dylib
    0x7fff6c020000 -     0x7fff6c020fff  libsystem_blocks.dylib (67) <F2493BB5-B1C6-3C4D-9F1F-1B402E0F1DB7> /usr/lib/system/libsystem_blocks.dylib
    0x7fff6c021000 -     0x7fff6c0aaff7  libsystem_c.dylib (1244.30.3) <E0136C71-0648-36F0-9F84-82EA2748A8D7> /usr/lib/system/libsystem_c.dylib
    0x7fff6c0ab000 -     0x7fff6c0aeffb  libsystem_configuration.dylib (963.30.1) <0F8D0B76-4F7D-34EC-AB6C-50F9465809DA> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6c0af000 -     0x7fff6c0b2ffb  libsystem_coreservices.dylib (51) <21A488D0-2D07-344E-8631-CC8B2A246F35> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff6c0b3000 -     0x7fff6c0b4fff  libsystem_darwin.dylib (1244.30.3) <2F750CB1-BC26-3FA3-AE59-553EE30D451B> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6c0b5000 -     0x7fff6c0bbff7  libsystem_dnssd.dylib (878.30.4) <EB9BB165-45A4-367C-B33A-688D4F383A95> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff6c0bc000 -     0x7fff6c105ff7  libsystem_info.dylib (517.30.1) <7D79E167-4B5C-3833-81EE-3AF3FB53616D> /usr/lib/system/libsystem_info.dylib
    0x7fff6c106000 -     0x7fff6c12bff7  libsystem_kernel.dylib (4570.31.3) <D2E842AA-3B8D-31BF-8234-8C1BE11CFE32> /usr/lib/system/libsystem_kernel.dylib
    0x7fff6c12c000 -     0x7fff6c177fcb  libsystem_m.dylib (3146) <ABB1B85F-9FFE-31B8-AD4F-E39A30794A93> /usr/lib/system/libsystem_m.dylib
    0x7fff6c178000 -     0x7fff6c197fff  libsystem_malloc.dylib (140.1.1) <9F0745FF-B92F-330D-8812-BB74001D1D33> /usr/lib/system/libsystem_malloc.dylib
    0x7fff6c198000 -     0x7fff6c23cff3  libsystem_network.dylib (1229.30.11) <40BAD301-8744-3AD8-A688-E7925C587B00> /usr/lib/system/libsystem_network.dylib
    0x7fff6c23d000 -     0x7fff6c247ffb  libsystem_networkextension.dylib (767.30.7) <C5ED4BAB-2480-369D-8AB6-DFB37C15A1EE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff6c248000 -     0x7fff6c251ff3  libsystem_notify.dylib (172) <98EA3D62-7C86-30DE-8261-D020D2F1EFF3> /usr/lib/system/libsystem_notify.dylib
    0x7fff6c252000 -     0x7fff6c259ff7  libsystem_platform.dylib (161.20.1) <C049250F-8C35-314D-810F-4E28AEAED983> /usr/lib/system/libsystem_platform.dylib
    0x7fff6c25a000 -     0x7fff6c265fff  libsystem_pthread.dylib (301.30.1) <ABA848E1-6978-3B42-A3A7-608B2C36FA93> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6c266000 -     0x7fff6c269ff3  libsystem_sandbox.dylib (765.30.4) <A51828BA-26D8-3205-AF3A-DF5C37269468> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6c26a000 -     0x7fff6c26bff3  libsystem_secinit.dylib (30) <F06ADB8F-9E94-34A7-B3C9-2C22FDD14BAD> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6c26c000 -     0x7fff6c273ff7  libsystem_symptoms.dylib (820.30.7) <DC3586C2-AA56-3419-88D3-FC0DBF08E3C0> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6c274000 -     0x7fff6c287ff7  libsystem_trace.dylib (829.30.14) <69EBF017-D40F-30D7-9B0B-BFC862D761A5> /usr/lib/system/libsystem_trace.dylib
    0x7fff6c289000 -     0x7fff6c28eff7  libunwind.dylib (35.3) <6D4FCD49-D2A9-3233-95C7-A7635CE265F2> /usr/lib/system/libunwind.dylib
    0x7fff6c28f000 -     0x7fff6c2bbff7  libxpc.dylib (1205.30.29) <F7E5F1BC-614B-39CB-B6CE-92A9C7B7EC0B> /usr/lib/system/libxpc.dylib

Model: MacBookPro11,3, BootROM MBP112.0142.B00, 4 processors, Intel Core i7, 2,6 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.37.5.1a3)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500,28 GB
USB Device: USB 3.0 Bus
USB Device: USB3.0 External HDD
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
`

**Comment by Yoyae** [comment]
Sorry to answer that late, you issue might have been solve already. If not, check the new version.
I'm closing this. If you feel the new version doesn't address the issue feel free to open a new one.
