### ISSUE TITLE
which one of the executable for windows 64 do we run for the wallet:

### ISSUE THREAD

**Issue by fynxgloire** [monacocoin-net/monoeci-core#8]
Hi,
which one of the executable for windows 64 do we run for the wallet:
monoeci-cli.exe
monoecid.exe
monoeci-tx.exe

**Comment by Yoyae** [comment]
Sorry to answer that late. Windows 64 exe can be found here : 
https://github.com/monacocoin-net/monoeci-core/releases
click on monoeciCore-0.12.2.3-wallet-win64.exe
