### ISSUE TITLE
Masternode error

### ISSUE THREAD

**Issue by paniccode** [monacocoin-net/monoeci-core#9]
when updating the server side masternode per the github instructions, 

after you enter  ./monoecid

error is created ./monoecid: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory

**Comment by fabar** [comment]
Me too.. it seems that the compiled version for Ubuntu needs the v.5 while the repos can just offer the 4.0 one (libzmq.so.4). need to recompile?

**Comment by seocrow** [comment]
Easiest way to fix this is to compile from source. I had the same issue and compiled on Ubuntu 17.

**Comment by Yoyae** [comment]
Sorry to answer that late, you issue might have been solve already. If not, check the new version.
I'm closing this. If you feel the new version doesn't address the issue feel free to open a new one.
